"""Added candidate_logs table

Revision ID: 8e981482a2be
Revises: 63a82540aa46
Create Date: 2025-02-12 14:01:04.024483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e981482a2be'
down_revision: Union[str, None] = '63a82540aa46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_email', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_logs_id'), 'candidate_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_logs_id'), table_name='candidate_logs')
    op.drop_table('candidate_logs')
    # ### end Alembic commands ###
